material_type: concrete

keywords:
  - value: Normalbeton
    level: high

  - value: Ortbeton
    level: high

  - value: Transportbeton
    level: high

  - value: Leichtbeton
    level: medium

  - value: Schwerbeton
    level: medium

  - value: WU-Beton
    level: medium

  - value: Sichtbeton
    level: medium

  - value: Pumpbeton
    level: medium

  - value: Faserbeton
    level: medium

  - value: Spritzbeton
    level: medium

  - value: Unterwasserbeton
    level: medium

  - value: Beton
    level: low

core_attributes:
  - strength_class
  - exposure_class
  - moisture_class
  - consistency_class
  - max_aggregate_size

supplementary_attributes:
  - concrete_type
  - density_class
  - chloride_class
  - cement_type
  - cement_strength_class
  - aggregate_type
  - air_entrained
  - fiber_type
  - self_compacting
  - water_cement_ratio
  - binder_content
  - special_properties