embedder:
  name: bge-m3
  path: ./models/embedding/bge-m3
  device: cuda
  trust_remote_code: false

# - name: multilingual-e5-large
#   path: ./models/embedding/multilingual-e5-large
#   device: cuda
#   trust_remote_code: false

reranker:
  name: bge-reranker-v2-m3
  path: ./models/reranker/bge-reranker-v2-m3
  device: cuda
  trust_remote_code: false