model:
  name: bge-m3
  path: ./models/embedding/bge-m3
  device: cuda
  trust_remote_code: false

# - name: multilingual-e5-large
#   path: ./models/embedding/multilingual-e5-large
#   device: cuda
#   trust_remote_code: false

# - name: jina-embeddings-v2-base-de
#   path: ./models/embedding/jina-embeddings-v2-base-de
#   device: cuda
#   trust_remote_code: true