name: consistency_class
type: single

values:
  # Setzmaß
  - S1
  - S2
  - S3
  - S4
  - S5

  # Vébé
  - V0
  - V1
  - V2
  - V3
  - V4

  # Verdichtungsmaß
  - C0
  - C1
  - C2
  - C3
  - C4

  # Ausbreitmaß
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6